# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain beta
    displayName: Install rust
  - script: $HOME/.cargo/bin/cargo test
    displayName: 'Cargo Test'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain beta
    displayName: Install rust
  - script: $HOME/.cargo/bin/cargo test
    displayName: 'Cargo Test'
